La base de datos ha sido actualizada
AugustoZp/ecommerce-unid-backend pull request #26
Opened 2023-02-10 21:58 UTC by AugustoZp

- Se corrigieron algunos campos con atribuciones erróneas.
- Se agregaron algunos campos faltantes a las tablas.

2023-02-10 22:34 UTC, GilbertoChan approved these changes

2023-02-10 22:40 UTC, GilbertoChan commented
Checando la codificación de la base de datos, no encontré algún error, mas que la duda sobre las imágenes que se están manejando por varchar? pero fuera de eso, todo esta bien

2023-02-10 23:59 UTC, Inge-Luis-Chan-Ku commented
Se valida  codificación de la base de datos, no se encuentra algún error

2023-02-10 23:59 UTC, DIVSZ requested changes
La base de datos la veo bien en general, si acaso solo sería el mencionar algunas modificaciones para que las tengamos en cuenta. 

En La tabla “categoríes” podríamos agregar un campo "unique" en “name”, ya que se van a manejar por marcas, producto line, o figuras articuladas, etc. y pues no debe haber duplicidad como tener 2 apartados para los funkos o nendoroid… Etc.

En la tabla “users” en "email" podemos agregarle un campo “unique” ya que no puedes tener 2 usuarios con el mismo correo o en su caso que este mismo se cree otra cuenta con el mismo correo.

2023-02-11 00:34 UTC, DIVSZ approved these changes
perfecto

2023-02-11 00:39 UTC, merged

2023-02-14 00:16 UTC, abraham1669 reviewed
¿Quién aprobó esto?

2023-02-14 00:16 UTC, abraham1669 commented on ecommerce-unid.sql
> +  `seller_id` int(3) NOT NULL,
Para qué servirá el campo seller_id en las categorías?

2023-02-14 00:16 UTC, abraham1669 commented on ecommerce-unid.sql
> +  `user_email` varchar(55) NOT NULL,
Para qué sirve el user_email dentro de orders, si se puede recuperar con el user_id?

2023-02-14 00:16 UTC, abraham1669 commented on ecommerce-unid.sql
> +  `order_address` varchar(200) NOT NULL,
Esto está bien, pero como van a enlazar un usuario a una dirección?

2023-02-14 00:16 UTC, abraham1669 commented on ecommerce-unid.sql
> +  `product_name` varchar(45) NOT NULL,
Para qué quiero el nombre del producto aquí, si lo puedo recuperar de la tabla de productos?

2023-02-14 00:16 UTC, abraham1669 commented on ecommerce-unid.sql
> +  `order_address` varchar(200) NOT NULL,
Para que quiero la dirección de la orden en el detalle, si adicional ya la tengo en la orden?

2023-02-14 00:16 UTC, abraham1669 commented on ecommerce-unid.sql
> +  `city` varchar(50) NOT NULL,
Qué sentido tiene city y state en el detalle de la orden?

2023-02-14 00:16 UTC, abraham1669 commented on ecommerce-unid.sql
> +  `total_amount` int(6) NOT NULL
Creo que no debe de ser total_amount, debe de ser price

2023-02-14 00:16 UTC, abraham1669 commented on ecommerce-unid.sql
> +  `seller_id` int(3) NOT NULL,
Para que necesito un seller_id aquí?

2023-02-14 00:16 UTC, abraham1669 commented on ecommerce-unid.sql
> +  `quantity` int(5) NOT NULL,
Le cambiaría el nombre a stock para ser más descriptivo

2023-02-14 00:16 UTC, abraham1669 commented on ecommerce-unid.sql
> +  `available` tinyint(1) NOT NULL DEFAULT 1
Si ya tienes quantity o stock, no necesitas avaiable, ya que, si quantity esta en 0, entonces no esta avalable

2023-02-14 00:16 UTC, abraham1669 commented on ecommerce-unid.sql
> +  `role` tinyint(1) NOT NULL DEFAULT 2,
Si es la tabla de sellers, entonces el rol debe de ser siempre sellers?