Correción de campos de base de datos
AugustoZp/ecommerce-unid-backend pull request #30
Opened 2023-02-15 01:02 UTC by DIVSZ

-Se eliminaron algunos campos innecesarios en la base de datos.

2023-02-15 16:03 UTC, AugustoZp requested changes
¿No es mejor idea colocar los roles en una tabla por separado?

2023-02-15 16:03 UTC, AugustoZp commented on DB/ecommerce_unid.sql
> +  `role` enum('user','admin') NOT NULL,
Creo que el campo role en la tabla users no es adecuado

2023-02-15 16:17 UTC, AugustoZp requested changes

2023-02-15 16:17 UTC, AugustoZp commented on DB/ecommerce_unid.sql
> +  `role` enum('user','admin') NOT NULL,
Podrías convertirlo en role_id y relacionarlo a una tabla adicional de roles

2023-02-15 19:22 UTC, AugustoZp approved these changes
La tabla de roles se ve adecuada, está correctamente relacionada y tiene los tipos de datos correctos.

2023-02-16 02:56 UTC, manuel-pech approved these changes

2023-02-16 02:58 UTC, merged

2023-02-16 03:00 UTC, manuel-pech approved these changes
estoy desacuerdo con el comentario de que tenga su propia tabla los roles, de ese modo seria mas fácil saber cuales son los roles que tiene el usuario, por lo general el código esta bien