Se crearon clases y método POST
AugustoZp/ecommerce-unid-backend pull request #35
Opened 2023-02-20 06:45 UTC by Antonio2254

- Se crearon las clases de todas las tablas
- Se crearon las rutas de index para las clases
- Se agregó la Consulta POST para insertar registros

//El colaborador Cezzane no tuvo presencia en la creación del código//

2023-02-20 20:03 UTC, AugustoZp commented on index.php
> +//////////Esta comnetodo porque no es necesario insertar nuevos roles, por el momento//////////
¿Está qué?

2023-02-20 20:04 UTC, AugustoZp commented on index.php
> +//////////Esta comnetodo porque no es necesario insertar nuevos roles, por el momento//////////
¿Está qué?

2023-02-20 20:06 UTC, AugustoZp requested changes
Faltas ortográficas en los comentarios, no permite entender bien el mensaje.

2023-02-20 22:40 UTC, manuel-pech approved these changes
Esta muy bien elaborado, 
la estructura del código esta decente

2023-02-20 22:41 UTC, AugustoZp approved these changes
Las correcciones se han realizado, el código está bien estructurado. Las consultas se probaron y funcionan sin problemas.

2023-02-20 22:44 UTC, merged

2023-02-20 23:18 UTC, Carrillo5308 commented
El código se ha mejorado y es satisfactorio por la parte de back, es necesario juntarlo con un poco de front para darle estructura, pero en general, fuera de lso comentarios anteriores, se está avanzando por buen camino

2023-02-20 23:46 UTC, GilbertoChan commented
Estuve revisando parte por parte y no encontré alguna anomalía que pudiera afectar el código, está toro estructurado de manera correcta y comprenderlo es sencillo

2023-02-20 23:50 UTC, Serchrc25 commented
Cuenta con una buena estructura para poder tener una sólida base del sitio y poder seguir construyendo de manera adecuada. Por lo que al juntarlo con el front, se tendrá un gran avance del sitio de modo que el proyecto va a buen ritmo.

2023-02-21 06:45 UTC, DIVSZ commented
Todo lo veo correctamente, se ha seguido una estructura para que sea entendible entre todos los colaboradores