Se creo los JWT y variables de entorno
AugustoZp/ecommerce-unid-backend pull request #44
Opened 2023-03-13 22:08 UTC by GilbertoChan

Se crearon las JWT, validando las rutas y con sus variables de entorno

2023-03-13 23:40 UTC, Antonio2254 requested changes, later dismissed
El archivo .env NO debe de estar visible, es importante agregarlo en el gitignore

2023-03-14 03:57 UTC, Inge-Luis-Chan-Ku approved these changes
En general, el código proporciona una implementación de autenticación basada en token, no presenta errores ortográficos 
 ValidateToken   GetToken

2023-03-15 01:14 UTC, Serchrc25 commented
La contraseña de los usuarios se almacena como un script simple, lo que es inseguro. Recomiendo utilizar un algoritmo de hashing para almacenar las contraseñas de manera segura.
El código no utiliza ningún mecanismo de autenticación o autorización para proteger los endpoints de la API. Sería bueno agregar un mecanismo de autenticación y autorización para restringir el acceso a los endpoints solo a los usuarios autorizados.
Fuera de ello, el código pinta con buena estructura, eficaz y legible.

2023-03-15 01:16 UTC, AugustoZp approved these changes
Ya probé que todas las rutas estén funcionando correctamente a través de insomnia, no encontré ningún error de sintaxis. Todo está bien estructurado y comentado, Los tokens se generan y se validan correctamente. Buen trabajo.

2023-03-15 01:28 UTC, Serchrc25 approved these changes

2023-03-16 02:36 UTC, merged